---
general:
  data_path: "/data/repo/"
  tmp_path: "/tmp/repo/"
  timeout: 60
  debounce: 120
  auto_align: 3600
repo:
  - name: centos8
    source:
      endpoint: https://
      kind: debian
      username: username
      password: password
    destination:
      s3: s3://s3repo/prod
      cdn_arn: arn
      access_key: key
      secret: secret
  - name: ubuntu
    versions:
      - xenial
      - bionic
      - focal
    source:
      endpoint: https://
      kind: debian
      username: username
      password: password
    destination:
      s3: s3://s3repo/prod
      cdn_arn: arn
      access_key: key
      secret: secret
