use axum::extract::{Path, State};
use axum::http::StatusCode;
use axum::response::IntoResponse;
use axum::routing::{get, post};
use axum::{Json, Router};
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};

use crate::sync::SyncManager;

/// Status of a repository — previously generated by swagger, now owned directly.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Status {
    pub name: String,
    pub status: String,
    pub next_sync: i64,
    pub last_sync: i64,
    pub last_result: String,
    pub size: i64,
    pub packages: isize,
}

pub async fn create(sync_manager: SyncManager, addr: &str) {
    let shared = Arc::new(sync_manager);
    SyncManager::start_scheduler(shared.clone());

    let app = Router::new()
        .route("/health", get(health_get))
        .route("/repository/{repo}", get(repository_repo_get))
        .route("/repository/{repo}/sync", post(repository_repo_sync_post))
        .with_state(shared);

    let listener = tokio::net::TcpListener::bind(addr)
        .await
        .expect("Failed to bind address");
    println!("starting http server, listening on  {}", addr);
    axum::serve(listener, app)
        .await
        .expect("HTTP server error");
}

fn normalize(system_time: &SystemTime) -> i64 {
    system_time.duration_since(UNIX_EPOCH).unwrap().as_millis() as i64
}

fn get_repo_status(sync_manager: &SyncManager, repo_name: &str) -> Option<Status> {
    let result = sync_manager.load_current_by_name(repo_name);
    if let Ok(Some(result)) = result {
        let (repo, _metadata) = result;
        if let Some(sync_state) = sync_manager.get_status(&repo.name) {
            Some(Status {
                status: sync_state.current.to_string(),
                next_sync: normalize(&sync_state.next_sync),
                last_sync: normalize(&sync_state.last_sync),
                last_result: sync_state.last_result.unwrap_or("".into()),
                name: repo.name.clone(),
                size: repo.size() as i64,
                packages: repo.count_packages() as isize,
            })
        } else {
            None
        }
    } else {
        None
    }
}

/// GET /health — simple health-check
async fn health_get(State(sm): State<Arc<SyncManager>>) -> impl IntoResponse {
    if let Err(err) = sm.check_permissions() {
        println!("health-check failed: {}", err);
        StatusCode::SERVICE_UNAVAILABLE
    } else {
        StatusCode::OK
    }
}

/// GET /repository/{repo} — status of repository
async fn repository_repo_get(
    State(sm): State<Arc<SyncManager>>,
    Path(repo): Path<String>,
) -> impl IntoResponse {
    if let Some(status) = get_repo_status(&sm, &repo) {
        Ok(Json(status))
    } else {
        Err(StatusCode::NOT_FOUND)
    }
}

/// POST /repository/{repo}/sync — trigger a synchronization
async fn repository_repo_sync_post(
    State(sm): State<Arc<SyncManager>>,
    Path(repo): Path<String>,
) -> impl IntoResponse {
    sm.queue_sync(&repo);
    if let Some(status) = get_repo_status(&sm, &repo) {
        Ok(Json(status))
    } else {
        Err(StatusCode::NOT_FOUND)
    }
}
